#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2013-05-23

description: >
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
    default: heat_key

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: ubuntu-wily-cloudimg
      flavor: m1.heat
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo db_port
          params:
            db_port: { get_param: key_name }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
